from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.registerpage),
    path('userlogin/', views.userlogin),
    path('homepage/', views.homepage, name='home'),
    path('homepage/', views.homepage, name='profile'),
    path('homepage/', views.homepage, name='notifications'),
    path('homepage/', views.homepage, name='teams'),
    path('homepage/', views.homepage, name='portfolio'),
    path('homepage/', views.homepage, name='tickets'),
    path('homepage/',views.homepage,name='admin'),
    path('homepage/', views.homepage, name='logout'),
    path('entrypage/', views.entrypage,name='entrypage'),
    path('tickets/', views.tickets, name='tickets'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('adminlogin/',views.adminlogin,name='admin'),
    path('projectdetails/',views.projectdetails),
    path('projectdetails_delete/<int:id>/',views.projectdetails_delete,name='projectdetails_delete'),
    path('projectstatus/',views.projectstatus),
    path('projectreport/',views.projectreport),
    path('projectreport_delete/<int:id>/',views.projectreport_delete,name='projectreport_delete'),
    path('taskreport_delete/<int:id>/',views.taskreport_delete,name='taskreport_delete'),
    path('profile_delete/<int:id>/',views.profile_delete,name='profile_delete'),
    path('logout/',views.logout, name='logout'),
    path('tasks/',views.tasks),
    path('workload/',views.workload),
    path('taskreport/',views.taskreport),
    path('profile/<int:id>/',views.profile,name='profile'),
    path('teamsentry/',views.teamsentry),
    path('teams',views.teams,name='teams'),
    path('teams_delete/<int:id>/',views.teams_delete,name='teams_delete'),
    path('notifications/',views.notifications,name='notifications'),
    path('notifications_delete/<int:id>/',views.notifications_delete,name='notifications_delete'),
    path('home/',views.home,name='home'),
    path('access/',views.access,name='access'),
]
