# Generated by Django 4.0.7 on 2023-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(choices=[('IT', 'It'), ('EC', 'Electronic'), ('BK', 'Bank'), ('OT', 'Other')], default='IT', max_length=30)),
                ('Title', models.TextField()),
                ('Startdate', models.DateField()),
                ('Enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='registerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=40)),
                ('Lastname', models.CharField(max_length=40)),
                ('Positiontitle', models.CharField(max_length=40)),
                ('Gender', models.CharField(max_length=20)),
                ('Dateofbirth', models.DateField()),
                ('Address', models.CharField(max_length=30)),
                ('Postalcode', models.IntegerField()),
                ('Phonenumber', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
