# Generated by Django 4.0.7 on 2023-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='Batch',
            field=models.CharField(choices=[('TM', 'Team'), ('IND', 'Individual'), ('OT', 'Other')], default='Team', max_length=30),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='Priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Veryhigh', 'Veryhigh')], default='Low', max_length=30),
        ),
    ]
