# Generated by Django 4.0.7 on 2023-02-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtracking', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teamname', models.CharField(max_length=50)),
                ('Projectname', models.CharField(max_length=50)),
                ('Progresstasks', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Tasks', models.CharField(max_length=50)),
            ],
        ),
    ]
