# Generated by Django 4.0.7 on 2023-02-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtracking', '0004_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projectname', models.CharField(max_length=50)),
                ('Employeename', models.CharField(max_length=50)),
                ('Completedwork', models.CharField(max_length=100)),
                ('Remainingwork', models.CharField(max_length=100)),
                ('Overduework', models.CharField(max_length=100)),
            ],
        ),
    ]
