# Generated by Django 4.0.7 on 2023-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtracking', '0005_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='Remainingwork',
            field=models.CharField(max_length=50),
        ),
    ]
