# Generated by Django 4.0.7 on 2023-02-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtracking', '0006_alter_load_remainingwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeerole', models.CharField(choices=[('PO', 'Product Owner'), ('PM', 'Product Manager'), ('SA', 'Software Architect'), ('DV', 'Developer'), ('DS', 'Designer'), ('QA', 'Quality Assurance'), ('BA', 'Business Analyst')], default='Developer', max_length=50)),
                ('Employeename', models.CharField(max_length=50)),
                ('Projectname', models.CharField(max_length=50)),
                ('Teamname', models.CharField(max_length=50)),
                ('Teamlength', models.CharField(max_length=50)),
            ],
        ),
    ]
