# Generated by Django 4.0.7 on 2023-02-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questtracking', '0007_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Email',
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
